### ISSUE TITLE
[Feature Request] Add support for embed

### ISSUE THREAD

**Issue by u8Jj3** [WD200019/alias#2]
Well not so much more to say, could be really cool to add support for embeded alias. :)

**Comment by Eir-nya** [comment]
I'm not sure that's possible, unfortunately.

Alias uses Powercord's commands library to send messages, and that system in turn uses the "monkeyPatchMessages" library. I've investigated it, and as far as I'm able to tell, embeds only work for Clyde's messages (Discord's bot that tells you if you failed to send a message or something. You can see what I mean with Powercord's `echo` command)

I've tried manipulating my code that sends a Clyde message if an alias doesn't exist, but trying to actually send a message with an embed instantly crashes Powercord. It doesn't just put an error in the console, Discord itself instantly dies. That's not a good sign.

I would love to implement embeds (with a warning about using them wisely ofc) but at the moment it just doesn't seem possible. I'm sorry :(

**Comment by u8Jj3** [comment]
Hi, thx for your response! There is no problem, this is not your fault in all case. Waiting for some Powercord updates to get thoses working! :)

Thx for your plugins btw :-)
